version: "3.8"
services:
  era-indexer-service:
    image: file-market-era-indexer-service:latest
    ports:
      - "9302:9302"
    depends_on:
      - era-indexer-postgres
      - era-indexer-redis
      - era-healthcheck-service
    volumes:
      - ~/era-logs:/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  era-oracle-service:
    image: file-market-era-oracle-service:latest
    depends_on:
      - era-oracle-redis
    volumes:
      - ~/era-logs:/logs
    restart: unless-stopped
  era-healthcheck-service:
    image: file-market-era-healthcheck-service:latest
    volumes:
      - ~/era-logs:/logs
    restart: unless-stopped
  era-oracle-redis:
    image: redis:7
    volumes:
      - era-cache-redis-data:/data
    command: redis-server --save 60 1
  era-indexer-postgres:
    image: postgres:13
    volumes:
      - era-indexer-postgres-data:/var/lib/postgresql/data
    env_file: ~/.era_indexer_pg_env
    restart: unless-stopped
    healthcheck:
      test: pg_isready -d file_market_indexer -U indexer
      interval: 10s
      timeout: 5s
      retries: 5
  era-indexer-redis:
    image: redis:7
    volumes:
      - era-indexer-redis-data:/data
    command: redis-server --save 60 1
  era-indexer-postgres-migration:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    env_file: ~/.era_indexer_pg_env
    depends_on:
      - era-indexer-postgres

volumes:
  era-indexer-postgres-data:
  era-cache-redis-data:
  era-indexer-redis-data: